import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {Providers} from './Providers'
import {Sidebar} from '@/components/slider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body className={inter.className}>

        <Providers>
          <Navbar/>
          <div className="flex">
          <Sidebar />
          {children}
          </div>
        </Providers>
        
        </body>
    </html>
  );
}
